web/apps/utilisateur/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .forms import ConnexionForm
from .views import deconnexion, reset_complete, \
    admin_user, user_view, password_change, user_info_change, admin_all_users, \
    admin_delete_user, all_users, \
    public_profile, get_user_cgu_consent, get_user_inscription, \
    get_user_profile_picture, nom_oublie, inscription, PasswordResetView, \
    valider, valider_cotisation, administrators

urlpatterns = [
    path('', user_view, name='utilisateur'),
    path('nom_d_utilisateur/', nom_oublie, name="username"),
    path('inscription/fiche/<int:user_id>', get_user_inscription,
         name="fiche_inscription"),
    path('photo/<int:user_id>', get_user_profile_picture,
         name="photo_utilisateur"),
    path('cgu/fiche/<int:user_id>', get_user_cgu_consent, name="fiche_cgu"),
    path('tous/admin/', admin_all_users, name="admin_all_users"),
    path('bureaux/', administrators, name="administrators"),
    path('tous/', all_users, name="all_users"),
    path('<int:uuid>/public/', public_profile, name="public_profile"),
    path('modification/<int:uuid>', admin_user, name="admin_user"),
    path('suppression/<int:uuid>', admin_delete_user,
         name="admin_delete_user"),
    path('inscription/', inscription, name='inscription'),
    path('modification/', user_info_change, name='modification_compte'),
    path('connexion/',
         auth_views.LoginView.as_view(authentication_form=ConnexionForm),
         name='connexion'),
    path('deconnexion/', deconnexion, name='deconnexion'),
    path('mot_de_passe/', password_change, name='modification_mot_de_passe'),
    path('mot_de_passe/reinitialisation/', PasswordResetView.as_view(),
         {'post_reset_redirect': '/#/login?resetemail=true'},
         name="password_reset"),
    path('mot_de_passe/reinitialisation/ok/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('mot_de_passe/reinitialisation/confirmation/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('mot_de_passe/reinitialisation/fini', reset_complete,
         name='password_reset_complete'),
    path('valider/<int:uuid>/<int:groupid>', valider,
         name='valider_utilisateur'),
    path('cotisation/<int:uuid>/<str:cotisid>', valider_cotisation,
         name='valider_cotisation'),
]

web/intramwet/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('intramwet.core.urls')),
    path('admin/', admin.site.urls),
    path('django-rq/', include('django_rq.urls'))
]

# Sentry testing
if settings.DEBUG:
    def trigger_error(request):
        division_by_zero = 1 / 0

    urlpatterns += path('sentry-debug/', trigger_error),

web/apps/utilisateur/models.py
import os
from datetime import datetime, timezone, date

from django.contrib.auth.models import AbstractUser, Group, Permission
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.templatetags.static import static
from django.utils.functional import cached_property
from icalendar import vCalAddress, vText


class Utilisateur(AbstractUser):
    anniversaire = models.DateField('anniversaire', null=True, blank=True)
    adresse = models.TextField('adresse', max_length=200, null=True,
                               blank=True)
    numeroDeTelephoneRegex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                            message="Le numéro de téléphone doit être entré au format '+999999999'. 15 chiffres maximum.")
    numeroDeTelephone = models.CharField('numéro de téléphone',
                                         validators=[numeroDeTelephoneRegex],
                                         max_length=17,
                                         null=True, blank=True)
    photo = models.ImageField(upload_to='photos_utilisateurs/', blank=True,
                              null=True)
    montantCaution = models.IntegerField('montant de la caution', default=0)
    numeroChequeDeCaution = models.IntegerField('numero de cheque', blank=True,
                                                null=True)

    ficheCGU = models.FileField(upload_to='cgu/', null=True, blank=True)

    valide = models.BooleanField("membre validé par le bureau", default=False)
    actif = models.BooleanField("membre actif pour l'année", default=True)

    NON_PAYEE = "ATT"
    PAYEE_ESP = "PES"
    PAYEE_CHQ = "PCH"
    PAYEE_VIR = "PVI"
    NON_NECESSAIRE = "INU"
    statutCotisation = models.CharField(
        max_length=3,
        choices=[
            (NON_PAYEE, "Non payée"),
            (PAYEE_ESP, "Payée en espèces"),
            (PAYEE_CHQ, "Payée par chèque"),
            (PAYEE_VIR, "Payée par virement"),
            (NON_NECESSAIRE, "Non nécessaire"),
        ],
        default=NON_NECESSAIRE,
    )

    organisation = models.ForeignKey('treso.Client', on_delete=models.PROTECT,
                                     null=True, blank=True,
                                     related_name='utilisateurs')

    def __str__(self):
        return "%s %s @%s" % (self.first_name, self.last_name, self.username)

    @cached_property
    def nomComplet(self):
        return "%s %s" % (self.first_name, self.last_name)

    @cached_property
    def photo_url(self):
        return self.photo.url if self.photo else static(
            'utilisateur/images/default-user.png')

    @cached_property
    def ficheInscription(self):
        today = datetime.now(timezone.utc)
        year = int(today.strftime('%Y'))
        if today.month < 9:
            debut = datetime(year=year - 1, month=9, day=1)
            fin = datetime(year=year, month=8, day=31, hour=23, minute=59,
                           second=59)
        else:
            debut = datetime(year=year, month=9, day=1)
            fin = datetime(year=year + 1, month=8, day=31, hour=23, minute=59,
                           second=59)
        return self.fichesInscription.all().filter(date__lt=fin,
                                                   date__gte=debut).order_by(
            '-date').first()

    @cached_property
    def vCalAddress(self):
        utilisateur = vCalAddress(f'MAILTO:{self.email}')
        utilisateur.params['cn'] = vText(self.nomComplet)
        return utilisateur

    @property
    def montant_cotisation(self) -> int:
        if self.statutCotisation != self.NON_NECESSAIRE:
            return CotisationGroupe.objects.get_for_user(user=self).cotisation
        return 0

    class Meta:
        permissions = (
            ('acceder_materiel', 'Peut accéder à la page materiel'),
            ('acceder_local', 'Peut accéder à la page d\'emprunt du local'),
            ('acceder_projets', 'Peut accéder à la page projets'),
            ('acceder_passation', "Peut accéder à l'interface de passation."),
            ('acceder_membres', "Peut accéder au module membres."),
            ('acceder_treso', "Peut accéder au module de tréso."),
            ('acceder_wiki', "Peut accéder au module wiki."),
            ('fiche_inscription',
             'Doit générer une fiche d\'inscription à la validation'),
            ('represente_organisation',
             'Peut représenter un client de l\'association')
        )


class StatutCA(models.Model):
    statut = models.CharField("Statut du membre au Conseil d'administration",
                              max_length=200)
    unique = models.BooleanField("Statut unique du poste CA", default=False)
    acceder_passation = models.BooleanField("Ce statut donne accès à l'interface de passation", default=False)
    acceder_treso = models.BooleanField("Ce statut donne accès à la tréso", default=False)
    acceder_su = models.BooleanField("Ce statut donne un accès super-utilisateur", default=False)

    PRESIDENT = "PRES"
    TRESORIER = "TRES"
    SECRETAIRE = "SECR"
    DEV = "DEV"
    AUTRE = "AUTR"
    GESTIONNAIRE_CINET = "CINT"
    poste = models.CharField(
        max_length=4,
        choices=[
            (PRESIDENT, "Président"),
            (TRESORIER, "Trésorier"),
            (SECRETAIRE, "Sécretaire"),
            (DEV, "Développeur"),
            (AUTRE, "Autre"),
            (GESTIONNAIRE_CINET, "Gestionnaire cinet'")
        ],
        default=AUTRE,
    )

    def __str__(self):
        return "%s" % self.statut


class MandatCA(models.Model):
    debut = models.DateField("Date de début du mandat", auto_now_add=True)
    fin = models.DateField("Date de fin du mandat", null=True, blank=True)

    @property
    def current(self) -> bool:
        return self.fin is None or self.fin > datetime.today().date()

    def __str__(self):
        return "Bureau actuel" if self.current else f"Du {self.debut} au {self.fin}"


@receiver(post_save, sender=MandatCA)
def remove_admin_rights_for_old_members(sender, instance: MandatCA,
                                        created: bool, **kwargs):
    for m in instance.membresCA.all():
        m.save(force_update=True)


class MembreCA(models.Model):
    statut = models.ForeignKey(StatutCA, on_delete=models.PROTECT)
    membre = models.ForeignKey(Utilisateur, on_delete=models.CASCADE,
                               related_name="postesCA")
    mandat = models.ForeignKey(MandatCA, on_delete=models.CASCADE,
                               related_name="membresCA")

    @property
    def current(self) -> bool:
        return self.mandat.current

    def set_admin_rights(self, save: bool = True):
        self.membre.is_staff = True
        self.membre.is_superuser = self.statut.acceder_su
        if self.statut.acceder_passation:
            permission = Permission.objects.get(codename='acceder_passation').id
            self.membre.user_permissions.add(permission)
        if self.statut.acceder_treso:
            permission = Permission.objects.get(codename='acceder_treso').id
            self.membre.user_permissions.add(permission)
        self.membre.save()
        if save:
            self.save()

    def remove_admin_rights(self, save: bool = True):
        if not self.membre.is_superuser:
            self.membre.is_staff = False
            self.membre.is_superuser = False
            if self.membre.has_perm('utilisateur.acceder_passation'):
                permission = Permission.objects.get(codename='acceder_passation').id
                self.membre.user_permissions.remove(permission)
            if self.membre.has_perm('utilisateur.acceder_treso'):
                permission = Permission.objects.get(codename='acceder_treso').id
                self.membre.user_permissions.remove(permission)
            self.membre.save()
            if save:
                self.save()

    def __str__(self):
        return "%s | %s" % (self.statut, self.membre)


@receiver(post_save, sender=MembreCA)
def set_admin_rights_on_membre_CA_saved(sender, instance: MembreCA,
                                        created: bool, **kwargs):
    if instance.mandat.current:
        instance.set_admin_rights(save=False)
    else:
        instance.remove_admin_rights(save=False)


class DescriptionGroupe(models.Model):
    group = models.OneToOneField(Group, on_delete=models.CASCADE,
                                 related_name='description')
    description = models.TextField("description du groupe", max_length=200)
    demandePrecisions = models.BooleanField(
        "nécessite des précisions supplémentaires", default=False)

    def __str__(self):
        return self.group.name


class CotisationGroupeManager(models.Manager):
    def get_for_user(self, user: Utilisateur):
        return self.filter(group__in=user.groups.all()).order_by('cotisation').first()


class CotisationGroupe(models.Model):
    group = models.OneToOneField(Group, on_delete=models.CASCADE,
                                 related_name='cotisation')
    cotisation = models.IntegerField(default=0)
    objects = CotisationGroupeManager()

    def __str__(self):
        return self.group.name


class FicheInscription(models.Model):
    utilisateur = models.ForeignKey(Utilisateur, on_delete=models.CASCADE,
                                    related_name='fichesInscription')
    fichier = models.FileField(upload_to='fiches_inscription/')
    date = models.DateField('Date de génération')

    def __str__(self):
        return "%s | %s" % (
            self.utilisateur.nomComplet, os.path.basename(self.fichier.name))

    @staticmethod
    def next_id():
        today = datetime.now(timezone.utc)
        if today.month < 9:
            debut = datetime(year=today.year - 1, month=9, day=1)
            fin = datetime(year=today.year, month=8, day=31, hour=23,

web/apps/utilisateur/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, \
    PasswordResetForm as auth_PasswordResetForm
from django.contrib.auth.models import Group
from django.contrib.auth.tokens import default_token_generator
from django.core.validators import RegexValidator
from django.forms import ModelForm, Form

from apps.conf.bot import Email
from .models import Utilisateur


class PhoneField(forms.CharField):
    default_validators = [RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                         message="Le numéro de téléphone doit être entré au format '+999999999'. 15 "
                                                 "chiffres maximum.")]


class InscriptionForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    anniversaire = forms.DateField()
    numeroDeTelephone = PhoneField(max_length=17)
    prefix = 'inscription'

    class Meta:
        model = Utilisateur
        fields = (
            'username', 'first_name', 'last_name', 'email', 'password1',
            'password2', 'anniversaire',
            'numeroDeTelephone', 'photo', 'adresse', 'groups')

    def __init__(self, *args, **kwargs):
        super(InscriptionForm, self).__init__(*args, **kwargs)
        self.fields['groups'] = forms.ModelChoiceField(
            queryset=Group.objects.all())

    def conforme_age_minimal(self):
        date_anniversaire = self.cleaned_data['anniversaire']
        age_minimal = 16
        age_utilisateur = (
                                  datetime.now().date() - date_anniversaire).days / 365
        if age_utilisateur < age_minimal:
            self.add_error("anniversaire",
                           "Vous devez être âgé d'au moins 16 ans pour vous inscrire sur ce site")
            return False
        return True

    def is_valid(self):
        valid = super().is_valid()
        self.conforme_age_minimal()
        return valid and self.conforme_age_minimal()


class ConnexionForm(AuthenticationForm):
    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request, *args, **kwargs)
        self.error_messages['invalid'] = "Votre compte n'est pas valide. Avant de pouvoir vous connecter, vous devez \
            attendre qu'un administrateur valide votre compte."

    def confirm_login_allowed(self, user):
        super().confirm_login_allowed(user)
        if not user.actif:
            user.actif = True
            user.save()

        if not user.valide:
            raise forms.ValidationError(
                self.error_messages['invalid'],
                code='invalid',
            )


class UsernameForgottenForm(Form):
    email = forms.EmailField(max_length=254)


class PasswordResetForm(auth_PasswordResetForm):
    """
        Surcharge du formulaire d'envoi de mail de reset de mdp pour pouvoir envoyer des mails en HTML
    """

    def save(self, domain_override=None,
             email_template_name='registration/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             request=None,
             email_subject_name='registration/password_reset_subject.txt',
             **kwargs):
        from django.utils.http import urlsafe_base64_encode
        from django.utils.encoding import force_bytes

        for user in self.get_users(self.cleaned_data["email"]):
            c = {
                'email': user.email,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': token_generator.make_token(user),
            }
            Email('emails/password_reset_email.html', user.email, c).send()


class ModificationForm(ModelForm):
    class Meta:
        model = Utilisateur
        fields = ('email', 'numeroDeTelephone', 'adresse', 'photo')


class AdminModificationForm(ModelForm):
    class Meta:
        model = Utilisateur
        fields = (
            'email', 'anniversaire', 'numeroDeTelephone', 'photo', 'adresse',
            'numeroChequeDeCaution', 'montantCaution',
            'valide', 'is_staff', 'groups', 'organisation'
        )

web/apps/utilisateur/templates/fiche_cgu.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</head>

<body>
<p>
    {{ NAME }} - {{ LEGAL_STATUS }}
    <br/>
    {% for line in ADDRESS %}
        {{ line }}
        <br/>
    {% endfor %}
    {{ ADDRESS_POSTAL_CODE }} {{ ADDRESS_CITY }} {% if ADDRESS_POSTAL_CODE_CEDEX %}CEDEX{% endif %} {{ ADDRESS_COUNTRY }}
    <br/>
</p>


<hr>

<h1>Fiche de consentement des conditions générales d'utilisation du site medialamouette.fr</h1>

<h2>Identité de l'utilisateur</h2>

<p>Numéro d'inscription : <b>{{ no_inscription }}</b></p>

<p>Nom : <b>{{ user.last_name }}</b></p>

<p>Prénom : <b>{{ user.first_name }}</b></p>

<p>Date de naissance : <b>{{ user.anniversaire|date }}</b></p>

<p>Adresse postale: <b>{{ user.adresse }}</b></p>

<hr>

<h2>Conditions générales d'utilisation acceptées</h2>

{{ cgu | safe }}

<hr>

<p>Fait le <b>{{ today|date:'l j F Y G:i:s e' }}</b>.</p>

</body>

</html>

web/apps/utilisateur/templates/profil.html
{% extends 'utilisateur.html' %}
{% load static %}

{% block title %}
    Mon profil
{% endblock %}

{% block head_css %}
    <link href="{% static 'utilisateur/css/profile.css' %}"
          rel="stylesheet" media="screen">
{% endblock %}

{% block footer_javascript %}
    <script src="{% static 'utilisateur/js/profile.js' %}"></script>
{% endblock %}

{% block content %}
    <header>
        <h1>Mon profil</h1>
    </header>

    <div class="container-fluid" style="margin-bottom: 50px;">
        <div class="row">
            <div class="col-xl-3 col-lg-5 col-md-5 order-md-12">
                <div class="card card-lg" id="user-info-card">
                    <h5 class="card-header">{{ user.nomComplet }}</h5>
                    <img alt="" src="{% url "photo_utilisateur" user.id %}" class="card-img-top">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-user-information">
                                    <tbody>

                                    <tr>
                                        <td>Nom d'utilisateur:</td>
                                        <td>{{ user.username }}</td>
                                    </tr>

                                    <tr>
                                        <td>Anniversaire:</td>
                                        <td>{{ user.anniversaire }}</td>
                                    </tr>
                                    <tr>
                                        <td>Groupes:</td>
                                        <td>
                                            {% for group in user.groups.all %}
                                                {{ group }}
                                            {% endfor %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Caution déposée:</td>
                                        <td>{{ user.montantCaution }} €</td>
                                    </tr>
                                    <tr>
                                        <td>Cotisation:</td>
                                        <td>{{ user.get_statutCotisation_display }}</td>
                                    </tr>
                                    </tbody>
                                </table>
                                {% if user.ficheInscription %}
                                    <a class="btn btn-primary" target="_blank"
                                       href="{% url "fiche_inscription" user.id %}" style="color:white;">Consulter ma
                                        fiche d'inscription</a>
                                {% endif %}
                                {% if user.ficheCGU %}
                                    <a class="btn btn-dark" target="_blank" href="{% url "fiche_cgu" user.id %}"
                                       style="color:white;">Consulter les CGU</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-9 col-lg-7 col-md-7 order-md-1">
                <div class="card card-lg" id="info-card">
                    <h5 class="card-header">Informations personnelles</h5>
                    <div class="card-body">
                        <form method="post" action="{% url 'modification_compte' %}" accept-charset="UTF-8"
                              enctype="multipart/form-data">
                            {% csrf_token %}

                            {{ info_form.non_field_errors }}

                            <div class="form-group">
                                {{ info_form.email.errors }}
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><h7><i
                                                class="fas fa-envelope"></i> Email</h7></span>
                                    </div>
                                    <input type="email" class="form-control" id="{{ info_form.email.id_for_label }}"
                                           name="{{ info_form.email.html_name }}"
                                           placeholder="{{ info_form.email.label }}"
                                           value="{{ info_form.email.value }}" required>
                                </div>
                            </div>


                            <div class="form-group">
                                {{ info_form.numeroDeTelephone.errors }}
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><h7><i class="fas fa-mobile"></i> Téléphone</h7></span>
                                    </div>
                                    <input type="tel" class="form-control"
                                           id="{{ info_form.numeroDeTelephone.id_for_label }}"
                                           name="{{ info_form.numeroDeTelephone.html_name }}"
                                           placeholder="{{ info_form.numeroDeTelephone.label }}"
                                           value="{{ info_form.numeroDeTelephone.value }}" required>
                                </div>
                            </div>


                            <div class="form-group">
                                {{ info_form.adresse.errors }}
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><h7><i
                                                class="fas fa-home"></i> Adresse</h7></span>
                                    </div>
                                    <textarea class="form-control" id="{{ info_form.adresse.id_for_label }}"
                                              name="{{ info_form.adresse.html_name }}"
                                              placeholder="{{ info_form.adresse.label }}"
                                              rows="3" required>{{ info_form.adresse.value }}</textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                {{ info_form.photo.errors }}
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><h7><i
                                                class="fas fa-camera-retro"></i> Photo</h7></span>
                                    </div>
                                    <input type="file" class="form-control"
                                           id="{{ info_form.photo.id_for_label }}"
                                           name="{{ info_form.photo.html_name }}"
                                           value="{{ info_form.photo.value }}">
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="submit" value="Sauvegarder"
                                               class="btn btn-primary btn-block"/>
                                        <input type="hidden" name="next" value="{{ next }}"/>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="card card-lg" id="password-card">
                    <h5 class="card-header">Mot de passe</h5>
                    <div class="card-body">
                        <form method="post" action="{% url 'modification_mot_de_passe' %}" accept-charset="UTF-8">

                            {% csrf_token %}
                            {{ password_form.non_field_errors }}

                            <div class="form-group">
                                {{ password_form.old_password.errors }}
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><h7><i class="fas fa-key"></i> Actuel</h7></span>
                                    </div>
                                    <input type="password" class="form-control"
                                           id="{{ password_form.old_password.id_for_label }}"
                                           name="{{ password_form.old_password.html_name }}"
                                           placeholder="Mot de passe actuel" required>
                                </div>
                            </div>

                            <div class="form-group">
                                {{ password_form.new_password1.errors }}
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><h7><i
                                                class="fas fa-key"></i> Nouveau</h7></span>
                                    </div>
                                    <input type="password" class="form-control has-popover"
                                           id="{{ password_form.new_password1.id_for_label }}"
                                           name="{{ password_form.new_password1.html_name }}"
                                           placeholder="Nouveau mot de passe" data-toggle="popover"
                                           data-container="body"
                                           data-html="true" data-placement="top"
                                           data-content="{{ password_form.new_password1.help_text|safe }}" required>
                                </div>
                            </div>

                            <div class="form-group">
                                {{ password_form.new_password2.errors }}
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><h7><i class="fas fa-key"></i> Confirmation</h7></span>
                                    </div>
                                    <input type="password" class="form-control has-popover"
                                           id="{{ password_form.new_password2.id_for_label }}"
                                           name="{{ password_form.new_password2.html_name }}"
                                           placeholder="Confirmez votre nouveau mot de passe" required>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <input type="submit" value="Changer mon mot de passe"
                                               class="btn btn-primary btn-block"/>
                                        <input type="hidden" name="next" value="{{ next }}"/>
                                    </div>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>


        </div>


    </div>





{% endblock %}

web/apps/utilisateur/templates/utilisateur.html
{% extends "base_navbar.html" %}

{% block navbar_compte %}
    active
{% endblock %}